import "./globals.css";
import Navbar from "@/components/Navbar";
import SpaceBackground from "@/components/SpaceBackground";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SpaceBackground />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
